### ISSUE TITLE
Command `ggA` clashes with `gga` under Windows

### ISSUE THREAD

**Issue by ankostis** [aspiers/git-config#7]
We are forced sometime to work on windows, and unfortunately relying on the case of the filenames does not work as expected.
So is it possible to rename the `bin/ggA` comamnds?

**Comment by aspiers** [comment]
Hmm, I'd prefer not to lose the ability to use `ggA` myself, since I find that convenient.  Could you simply do that rename as part of your process of installing the repo on Windows?  If that's awkward, let me know and maybe we can figure out another solution.

**Comment by ankostis** [comment]
Well, I doubt there is a "bloodless" solution under Windows; as soon as you clone repo,
you are always with `bin/ggA` as modified (overwritten by `gga` while checked-out).
Practically you cannot switch to any other branch, unlses usinng `git reset --hard` each time.

I see that `gga/ggA` is the only case where the names clash, so it should not be very invasive to fix it.

**Comment by aspiers** [comment]
Oh I see.  OK, I guess I don't use `gga` very much anyway, so I'll rename that to `ggan`, and rename `ggA` to `gga`.

**Comment by ankostis** [comment]
Great response time, thanks!
